name: Windows

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - '*'

permissions:
  contents: write

jobs:
  get-extension-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.extension-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Get extension matrix
        id: extension-matrix
        uses: php/php-windows-builder/extension-matrix@v1
        with:
          php-version-list: '8.3, 8.4, 8.5'

  build:
    needs: get-extension-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.get-extension-matrix.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Build extension
        uses: php/php-windows-builder/extension@v1
        env:
          MARKDOWN_VERSION: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}
        with:
          php-version: ${{ matrix.php-version }}
          arch: ${{ matrix.arch }}
          ts: ${{ matrix.ts }}

  release:
    needs: build
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Upload Windows release assets
        uses: php/php-windows-builder/release@v1
        with:
          release: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
